"extends":
  - "stylelint-config-recess-order"
  - "stylelint-config-recommended-scss"
  - "stylelint-prettier/recommended"
"plugin":
  - "stylelint-scss"
  - "stylelint-order"
"ignoreFiles":
  - "**/node_modules/**"
"rules":
  "prettier/prettier": true
  "function-calc-no-invalid": true
  "function-calc-no-unspaced-operator": true
  "declaration-block-no-duplicate-properties": true
  "at-rule-no-unknown": null
  "scss/at-rule-no-unknown":
    - true
  "no-descending-specificity": null